name: random_string
description: Simple library for generating random ascii strings.
version: 0.0.2
author: Damon Douglas <douglas.damon@gmail.com>
homepage: https://github.com/damondouglas/random_string.dart

environment:
  sdk: '>=1.0.0 <3.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
